import bcrypt from "bcrypt";

import { db, sqlite } from "@/db/index";
import {
  alumni,
  brandRules,
  calendarEvents,
  competitiveAlerts,
  competitorInsights,
  competitorMetrics,
  campaignKits,
  competitors,
  contentItems,
  kanbanCards,
  partners,
  personas,
  prompts,
  references,
  users,
  templates,
} from "@/db/schema";
import { TEMPLATE_SEEDS } from "@/lib/data/templates-seed";

function serializeList(...items: string[]): string {
  return JSON.stringify(items);
}

async function main() {
  const seedPassword = process.env.AUTH_SEED_PASSWORD ?? "CFI2026!";
  const passwordHash = await bcrypt.hash(seedPassword, 10);

  db.delete(users).run();
  db.delete(contentItems).run();
  db.delete(brandRules).run();
  db.delete(kanbanCards).run();
  db.delete(calendarEvents).run();
  db.delete(competitors).run();
  db.delete(competitorInsights).run();
  db.delete(competitorMetrics).run();
  db.delete(competitiveAlerts).run();
  db.delete(prompts).run();
  db.delete(personas).run();
  db.delete(alumni).run();
  db.delete(partners).run();
  db.delete(references).run();
  db.delete(campaignKits).run();
  db.delete(templates).run();

  db.insert(users).values([
    {
      name: "Laure Reymond",
      email: "laure.reymond@cfi.local",
      passwordHash,
      role: "admin",
      avatarUrl: null,
    },
    {
      name: "Mathilde Dupont",
      email: "mathilde.dupont@cfi.local",
      passwordHash,
      role: "editor",
      avatarUrl: null,
    },
    {
      name: "Thomas Martin",
      email: "thomas.martin@cfi.local",
      passwordHash,
      role: "editor",
      avatarUrl: null,
    },
    {
      name: "Claire Bernard",
      email: "claire.bernard@cfi.local",
      passwordHash,
      role: "reviewer",
      avatarUrl: null,
    },
  ]).run();

  const seedNow = new Date().toISOString();
  db.insert(templates)
    .values(
      TEMPLATE_SEEDS.map((seed) => ({
        slug: seed.slug,
        name: seed.name,
        description: seed.description,
        kind: seed.kind,
        formation: seed.formation ?? null,
        eventName: seed.eventName ?? null,
        audience: seed.audience ?? null,
        platform: seed.platform,
        tone: seed.tone,
        visualStyle: seed.visualStyle,
        duration: seed.duration,
        cta: seed.cta,
        structure: JSON.stringify(seed.structure),
        assets: JSON.stringify(seed.assets),
        briefSeed: seed.briefSeed,
        archived: false,
        createdAt: seedNow,
        updatedAt: seedNow,
      })),
    )
    .run();

  db.insert(contentItems).values([
    {
      title: "Reel motion : rush étudiants DCDG",
      format: "Reel",
      platform: "Instagram",
      campaign: "JPO Mai 2026",
      persona: "Lycéens 16-20",
      status: "published",
      dueDate: "2026-05-07T10:00:00+02:00",
      publishedAt: "2026-05-07T18:00:00+02:00",
      owner: "Laure Reymond",
      aiScore: 96,
      brandScore: 94,
    },
    {
      title: "Portrait alumni : Refika Dervišević",
      format: "Carrousel",
      platform: "Instagram",
      campaign: "Alumni",
      persona: "Alumni",
      status: "review",
      dueDate: "2026-05-16T09:30:00+02:00",
      owner: "Thomas L.",
      aiScore: 88,
      brandScore: 91,
    },
    {
      title: "Newsletter entreprises : workshop motion",
      format: "Newsletter",
      platform: "Email",
      campaign: "Partenariats",
      persona: "Entreprises partenaires",
      status: "brief",
      dueDate: "2026-06-03T14:00:00+02:00",
      owner: "Laure Reymond",
      aiScore: 82,
      brandScore: 90,
    },
    {
      title: "Carrousel : 5 raisons de choisir la Fonderie",
      format: "Carrousel",
      platform: "Instagram",
      campaign: "Recrutement étudiants",
      persona: "Parents",
      status: "planned",
      dueDate: "2026-05-10T17:30:00+02:00",
      owner: "Laure Reymond",
      aiScore: 89,
      brandScore: 92,
    },
    {
      title: "Behind-the-scenes atelier sérigraphie",
      format: "Reel",
      platform: "TikTok",
      campaign: "Showcase étudiants",
      persona: "Lycéens 16-20",
      status: "planned",
      dueDate: "2026-05-11T12:00:00+02:00",
      owner: "Thomas L.",
      aiScore: 91,
      brandScore: 88,
    },
    {
      title: "Teaser JPO — Compte à rebours",
      format: "Reel",
      platform: "Instagram",
      campaign: "JPO Mai 2026",
      persona: "Lycéens 16-20",
      status: "planned",
      dueDate: "2026-05-15T18:00:00+02:00",
      owner: "Laure Reymond",
      aiScore: 94,
      brandScore: 95,
    },
    {
      title: "Post LinkedIn alumni direction artistique",
      format: "Post",
      platform: "LinkedIn",
      campaign: "Alumni",
      persona: "Alumni",
      status: "published",
      dueDate: "2026-04-22T14:00:00+02:00",
      publishedAt: "2026-04-22T15:30:00+02:00",
      owner: "Laure Reymond",
      aiScore: 90,
      brandScore: 94,
    },
    {
      title: "Story campus — micro-trottoir Puces Typo",
      format: "Story",
      platform: "Instagram",
      campaign: "Showcase étudiants",
      persona: "Lycéens 16-20",
      status: "published",
      dueDate: "2026-04-19T16:00:00+02:00",
      publishedAt: "2026-04-19T17:00:00+02:00",
      owner: "Thomas L.",
      aiScore: 86,
      brandScore: 88,
    },
  ]).run();

  db.insert(brandRules).values([
    {
      category: "Palette",
      name: "Jaune institutionnel",
      description: "Utiliser #FFED00 et refuser toute dérive off-brand sur les slides CTA et admissions.",
      severity: "high",
      expectedValue: "#FFED00",
      status: "active",
    },
    {
      category: "Typographie",
      name: "Titres caps SVHFlib Bold",
      description: "Les titres doivent rester en capitales avec SVHFlib Bold pour les écrans de campagne.",
      severity: "high",
      expectedValue: "SVHFlib Bold uppercase",
      status: "active",
    },
    {
      category: "Conformité",
      name: "Mentions formation",
      description: "Toute promesse formation ou financement garde les mentions Qualiopi et RNCP utiles.",
      severity: "high",
      expectedValue: "Mentions présentes",
      status: "active",
    },
    {
      category: "Ton",
      name: "Tutoiement pour les lycéens",
      description: "Employer un ton direct, inspirant et accessible sur les contenus recrutement.",
      severity: "medium",
      expectedValue: "Tutoiement",
      status: "active",
    },
    {
      category: "CTA",
      name: "Repères JPO",
      description: "Les contenus JPO citent la date, le campus et le bénéfice visiteur dès le CTA final.",
      severity: "medium",
      expectedValue: "Date + campus + bénéfice",
      status: "active",
    },
  ]).run();

  db.insert(kanbanCards).values([
    {
      columnId: "ideas",
      title: "Interview prof typographie sur le Colloque",
      platform: "LinkedIn",
      persona: "Alumni",
      campaign: "Alumni",
      assignee: "Laure Reymond",
      dueDate: "2026-05-02T10:00:00+02:00",
      aiProgress: 12,
    },
    {
      columnId: "ideas",
      title: "Témoignage alumni Refika Dervišević",
      platform: "Instagram Reel",
      persona: "Alumni",
      campaign: "Alumni",
      assignee: "Thomas L.",
      dueDate: "2026-05-03T11:00:00+02:00",
      aiProgress: 8,
    },
    {
      columnId: "ideas",
      title: "Série « Une journée à l'atelier »",
      platform: "TikTok",
      persona: "Lycéens 16-20",
      campaign: "Showcase étudiants",
      assignee: "Laure Reymond",
      dueDate: "2026-05-04T09:00:00+02:00",
      aiProgress: 18,
    },
    {
      columnId: "brief",
      title: "Teaser Festival d'Annecy — workshops motion",
      platform: "Instagram",
      persona: "Entreprises partenaires",
      campaign: "Partenariats",
      assignee: "Thomas L.",
      dueDate: "2026-05-06T14:00:00+02:00",
      aiProgress: 34,
    },
    {
      columnId: "brief",
      title: "Post Parcoursup phase complémentaire",
      platform: "Instagram",
      persona: "Lycéens 16-20",
      campaign: "Parcoursup",
      assignee: "Laure Reymond",
      dueDate: "2026-05-07T16:00:00+02:00",
      aiProgress: 28,
    },
    {
      columnId: "production",
      title: "Reel JPO — Motion Design (variantes)",
      platform: "Instagram Reel",
      persona: "Lycéens 16-20",
      campaign: "JPO Mai 2026",
      assignee: "Thomas L.",
      dueDate: "2026-05-10T15:00:00+02:00",
      aiProgress: 72,
    },
    {
      columnId: "production",
      title: "Carrousel 5 raisons CFI",
      platform: "Instagram",
      persona: "Parents",
      campaign: "Recrutement étudiants",
      assignee: "Laure Reymond",
      dueDate: "2026-05-11T12:00:00+02:00",
      aiProgress: 58,
    },
    {
      columnId: "production",
      title: "Atelier sérigraphie BTS1",
      platform: "TikTok",
      persona: "Lycéens 16-20",
      campaign: "Showcase étudiants",
      assignee: "Thomas L.",
      dueDate: "2026-05-12T17:00:00+02:00",
      aiProgress: 44,
    },
    {
      columnId: "review",
      title: "Carrousel Motion Design · 5 slides",
      platform: "Instagram",
      persona: "Lycéens 16-20",
      campaign: "JPO Mai 2026",
      assignee: "Thomas L.",
      dueDate: "2026-05-14T10:00:00+02:00",
      aiProgress: 100,
      brandScore: 89,
    },
    {
      columnId: "review",
      title: "Photo campus — session lumière",
      platform: "Instagram",
      persona: "Parents",
      campaign: "Recrutement étudiants",
      assignee: "Laure Reymond",
      dueDate: "2026-05-15T09:30:00+02:00",
      aiProgress: 100,
      brandScore: 86,
    },
    {
      columnId: "validated",
      title: "Portrait alumni Refika",
      platform: "LinkedIn",
      persona: "Alumni",
      campaign: "Alumni",
      assignee: "Laure Reymond",
      dueDate: "2026-05-18T11:30:00+02:00",
      aiProgress: 100,
      brandScore: 94,
    },
    {
      columnId: "validated",
      title: "Brief Erasmus+ printemps",
      platform: "Email",
      persona: "Entreprises partenaires",
      campaign: "Partenariats",
      assignee: "Thomas L.",
      dueDate: "2026-05-19T14:00:00+02:00",
      aiProgress: 100,
      brandScore: 91,
    },
    {
      columnId: "validated",
      title: "Story Portes Ouvertes J-10",
      platform: "Instagram Reel",
      persona: "Lycéens 16-20",
      campaign: "JPO Mai 2026",
      assignee: "Laure Reymond",
      dueDate: "2026-05-20T18:00:00+02:00",
      aiProgress: 100,
      brandScore: 97,
    },
    {
      columnId: "published",
      title: "Reel workshop DCDG · vues 42k",
      platform: "Instagram Reel",
      persona: "Lycéens 16-20",
      campaign: "Showcase étudiants",
      assignee: "Thomas L.",
      dueDate: "2026-04-28T17:00:00+02:00",
      aiProgress: 100,
      brandScore: 93,
    },
    {
      columnId: "published",
      title: "Carrousel Puces Typo",
      platform: "Instagram",
      persona: "Entreprises partenaires",
      campaign: "Partenariats",
      assignee: "Laure Reymond",
      dueDate: "2026-04-25T10:00:00+02:00",
      aiProgress: 100,
      brandScore: 90,
    },
  ]).run();

  db.insert(calendarEvents).values([
    {
      title: "JPO de mai",
      eventType: "open_day",
      platform: "Multi-canal",
      campaign: "JPO Mai 2026",
      startDate: "2026-05-17T09:00:00+02:00",
      endDate: "2026-05-17T18:00:00+02:00",
      location: "Campus CFI Paris",
      aiSuggestion: "Créer un compte à rebours stories dès le 7 mai.",
    },
    {
      title: "Fenêtre Parcoursup",
      eventType: "recruitment",
      platform: "Instagram + LinkedIn",
      campaign: "Parcoursup",
      startDate: "2026-01-15T09:00:00+01:00",
      endDate: "2026-03-31T18:00:00+02:00",
      location: "France",
      aiSuggestion: "Préparer 4 rappels orientés parents et lycéens.",
    },
    {
      title: "Festival d'Annecy",
      eventType: "festival",
      platform: "Instagram Reel",
      campaign: "Showcase étudiants",
      startDate: "2026-06-14T09:00:00+02:00",
      endDate: "2026-06-20T19:00:00+02:00",
      location: "Annecy",
      aiSuggestion: "Monter une série backstage avec 3 rushs motion inexploités.",
    },
    {
      title: "Salons étudiants de printemps",
      eventType: "fair",
      platform: "LinkedIn + Stories",
      campaign: "Recrutement étudiants",
      startDate: "2026-03-12T09:00:00+01:00",
      endDate: "2026-03-27T18:00:00+01:00",
      location: "Paris et Lyon",
    },
    {
      title: "Rentrée de septembre",
      eventType: "school_year",
      platform: "Instagram + Email",
      campaign: "Rentrée 2026",
      startDate: "2026-09-01T08:00:00+02:00",
      endDate: "2026-09-15T18:00:00+02:00",
      location: "Campus CFI",
      aiSuggestion: "Ajouter 2 contenus alumni pour équilibrer le mois.",
    },
  ]).run();

  db.insert(competitors).values([
    {
      name: "Gobelins",
      handle: "@gobelins_paris",
      primaryPlatform: "Instagram",
      monthlyPosts: 128,
      deltaPercent: 12,
      positioning: "Narration premium et coulisses ateliers",
      opportunity: "Répondre avec un format process étudiant plus brut et plus incarné.",
    },
    {
      name: "LISAA",
      handle: "@lisaa_paris",
      primaryPlatform: "TikTok",
      monthlyPosts: 94,
      deltaPercent: 4,
      positioning: "Volumes forts sur les admissions et la vie de campus",
      opportunity: "Renforcer les témoignages vidéo autour de la JPO.",
    },
    {
      name: "ECV",
      handle: "@ecv_france",
      primaryPlatform: "LinkedIn",
      monthlyPosts: 82,
      deltaPercent: -2,
      positioning: "Focus employabilité et projets de fin d’études",
      opportunity: "Accélérer les contenus entreprises partenaires.",
    },
    {
      name: "Cifacom",
      handle: "@cifacom",
      primaryPlatform: "Instagram",
      monthlyPosts: 67,
      deltaPercent: 8,
      positioning: "Ton événementiel et rythme soutenu sur les stories",
      opportunity: "Monter une série stories Parcoursup plus claire et plus pédagogique.",
    },
  ]).run();
  const now = new Date().toISOString();

  const METRICS_HANDLES: Array<{
    handle: string;
    instagram: [number, number, number];
    linkedin: [number, number, number];
    tiktok: [number, number, number];
  }> = [
    { handle: "@cfi_paris", instagram: [14, 5.1, 48000], linkedin: [6, 4.2, 18000], tiktok: [3, 7.4, 12000] },
    { handle: "@gobelins_paris", instagram: [42, 8.2, 210000], linkedin: [12, 6.1, 82000], tiktok: [18, 11.2, 180000] },
    { handle: "@lisaa_paris", instagram: [28, 6.4, 140000], linkedin: [8, 4.8, 48000], tiktok: [26, 9.5, 220000] },
    { handle: "@ecv_france", instagram: [22, 5.6, 98000], linkedin: [16, 7.1, 110000], tiktok: [10, 6.2, 68000] },
    { handle: "@cifacom", instagram: [30, 4.9, 76000], linkedin: [5, 3.8, 24000], tiktok: [12, 5.1, 42000] },
  ];

  const WEEK_STARTS = ["2026-03-23", "2026-03-30", "2026-04-06", "2026-04-13"];
  const metricRows: Array<{
    handle: string;
    platform: string;
    weekStart: string;
    posts: number;
    engagementRate: number;
    reach: number;
  }> = [];
  WEEK_STARTS.forEach((weekStart, weekIdx) => {
    METRICS_HANDLES.forEach((entry) => {
      const mul = 0.78 + weekIdx * 0.08;
      (["Instagram", "LinkedIn", "TikTok"] as const).forEach((platform) => {
        const key =
          platform === "Instagram" ? entry.instagram : platform === "LinkedIn" ? entry.linkedin : entry.tiktok;
        metricRows.push({
          handle: entry.handle,
          platform,
          weekStart,
          posts: Math.round(key[0] * mul),
          engagementRate: Math.round(key[1] * mul * 10) / 10,
          reach: Math.round(key[2] * mul),
        });
      });
    });
  });
  db.insert(competitorMetrics).values(metricRows).run();

  db.insert(competitorInsights).values([
    {
      handle: "@gobelins_paris",
      summary: "Poussée forte sur les Reels BTS atelier, ton documentaire, tutoiement assumé.",
      highlights: JSON.stringify([
        "9 Reels behind-the-scenes en 14 jours",
        "Engagement moyen 8,2% sur Instagram",
        "Tutoiement + musique lente sur 80% des Reels",
      ]),
      opportunity: "Répondre avec un format process étudiant plus brut et plus incarné.",
      source: "seed",
      generatedAt: now,
    },
    {
      handle: "@lisaa_paris",
      summary: "Accélération TikTok, formats courts 15-30s, focus admissions et vie de campus.",
      highlights: JSON.stringify([
        "26 publications TikTok cette semaine",
        "Carrousels admissions +190%",
        "Stories workshop typographie saturées",
      ]),
      opportunity: "Renforcer les témoignages vidéo autour de la JPO.",
      source: "seed",
      generatedAt: now,
    },
    {
      handle: "@ecv_france",
      summary: "Focus LinkedIn employabilité, ton corporate, portraits alumni.",
      highlights: JSON.stringify([
        "16 posts LinkedIn cette semaine",
        "Engagement LinkedIn 7,1% (+0,6 pt)",
        "Réductions des formats courts sur Instagram",
      ]),
      opportunity: "Accélérer les contenus entreprises partenaires.",
      source: "seed",
      generatedAt: now,
    },
    {
      handle: "@cifacom",
      summary: "Cadence stories soutenue sur Parcoursup, formats événementiels.",
      highlights: JSON.stringify([
        "30 stories Parcoursup",
        "Carrousel « 5 erreurs » à 7,2%",
        "Pic d'activité en soirée",
      ]),
      opportunity: "Monter une série stories Parcoursup plus claire et plus pédagogique.",
      source: "seed",
      generatedAt: now,
    },
  ]).run();

  db.insert(competitiveAlerts).values([
    {
      handle: "@gobelins_paris",
      severity: "high",
      title: "Gobelins pousse 3x plus de Reels BTS",
      description: "9 Reels atelier publiés en 14 jours, engagement moyen 8,2%. Format court, tutoiement, musique lente.",
      source: "seed",
      dismissed: false,
      createdAt: now,
    },
    {
      handle: "@lisaa_paris",
      severity: "medium",
      title: "LISAA accélère sur TikTok",
      description: "26 publications TikTok cette semaine contre 11 la semaine précédente. Focus admissions.",
      source: "seed",
      dismissed: false,
      createdAt: now,
    },
    {
      handle: "@ecv_france",
      severity: "low",
      title: "ECV consolide son positionnement LinkedIn",
      description: "Engagement LinkedIn 7,1% (+0,6 pt). Séries portraits alumni et partenaires.",
      source: "seed",
      dismissed: false,
      createdAt: now,
    },
  ]).run();

  db.insert(prompts).values([
    {
      slug: "jpo-teaser-reel",
      title: "JPO · Teaser Reel",
      description: "Reel 15-30s pour teaser une journée portes ouvertes avec rushs étudiants.",
      category: "JPO & Events",
      audience: "Lycéens 16-20",
      platform: "Instagram Reel",
      tone: "purple",
      rating: 4.9,
      monthlyUsage: 24,
      variables: "{formation},{persona},{plateforme},{ton},{date_evenement},{hashtag_principal}",
      body: "Crée un {plateforme} de 30 secondes pour promouvoir la {date_evenement} de la Fonderie de l'Image.\n\nCible : {persona}. Ton éditorial : {ton}.\n\nMets en avant la formation {formation} avec des extraits de projets étudiants récents.\n\nContraintes : utiliser la palette CFI (noir #1D1D1B, violet #AE64DE, bleu #80D3FF, jaune #FFED00). Typo SVHFlib Bold en caps pour les titres. Tutoiement. Zéro jargon corporate.\n\nInclure le hashtag {hashtag_principal} + #FonderieDeLImage + #EcoleCreative + #Bagnolet.\n\nCTA final : « Viens voir IRL le 17 mai. Métro Gallieni. »",
      author: "Laure R.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "parcoursup-j14-story",
      title: "Parcoursup · J-14 story",
      description: "Série 3 stories countdown Parcoursup avec CTA inscription.",
      category: "Recrutement étudiants",
      audience: "Lycéens 16-20",
      platform: "Instagram Story",
      tone: "yellow",
      rating: 4.6,
      monthlyUsage: 18,
      variables: "{formation},{deadline},{preuve_sociale}",
      body: "Construis une série de 3 stories verticales countdown Parcoursup pour {formation}, avec deadline {deadline} et preuve sociale {preuve_sociale}. Pack jaune, tutoiement, CTA swipe-up vers formulaire.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "alumni-portrait-linkedin",
      title: "Alumni · Portrait LinkedIn",
      description: "Post LinkedIn long format, citation + parcours + projet signature.",
      category: "Alumni",
      audience: "Alumni",
      platform: "LinkedIn",
      tone: "caramel",
      rating: 4.8,
      monthlyUsage: 16,
      variables: "{alumni},{emploi},{projet_signature}",
      body: "Rédige un post LinkedIn long format présentant {alumni}, aujourd'hui {emploi}. Structure : citation d'accroche, parcours CFI, projet signature {projet_signature}, conseil aux jeunes diplômés.",
      author: "Laure R.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "bts-motion-showcase",
      title: "BTS Motion · showcase projet",
      description: "Carrousel 6 slides pour mettre en avant un projet étudiant motion.",
      category: "Showcase étudiants",
      audience: "Lycéens 16-20",
      platform: "Instagram",
      tone: "sky",
      rating: 4.7,
      monthlyUsage: 14,
      variables: "{projet},{logiciel},{etudiant}",
      body: "Propose un carrousel 6 slides pour le projet {projet} de {etudiant}, en mettant {logiciel} en avant. Slide 1 : visuel fort. Slide 2-4 : process. Slide 5 : résultat. Slide 6 : CTA découverte BTS.",
      author: "Thomas L.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "atelier-behind-the-scenes",
      title: "Behind-the-scenes atelier",
      description: "Reel 45s format tutoiement, musique lente, sous-titres jaune.",
      category: "Life on campus",
      audience: "Lycéens 16-20",
      platform: "Instagram Reel",
      tone: "green",
      rating: 4.9,
      monthlyUsage: 22,
      variables: "{atelier},{formation}",
      body: "Écris un script de Reel 45 secondes, POV entrée en {atelier}. Tutoiement, musique lente, sous-titres jaune CFI. Termine sur le logo {formation} + main qui claque.",
      author: "Laure R.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "parents-fiche-formation",
      title: "Parents · Fiche formation",
      description: "Post Instagram informatif, ton pédagogique, données concrètes.",
      category: "Recrutement étudiants",
      audience: "Parents d'étudiants",
      platform: "Instagram",
      tone: "sky",
      rating: 4.3,
      monthlyUsage: 9,
      variables: "{formation},{insertion},{partenaires}",
      body: "Crée un post Instagram fiche formation pour {formation}. Inclure : 3 chiffres clés d'{insertion}, liste {partenaires}, ton vouvoiement, rassurant. CTA : télécharger la brochure.",
      author: "Thomas L.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "partenaire-workshop-annonce",
      title: "Partenaire · annonce workshop",
      description: "Post co-brandé avec logos partenaire, carrousel 4 slides.",
      category: "Partenariats",
      audience: "Entreprises partenaires",
      platform: "LinkedIn",
      tone: "pink",
      rating: 4.5,
      monthlyUsage: 7,
      variables: "{entreprise},{atelier},{date}",
      body: "Compose un post LinkedIn annonçant le partenariat avec {entreprise} autour de {atelier} le {date}. Carrousel 4 slides : intro, briefs, livrables étudiants, témoignage. Logos co-brandés en slide 1.",
      author: "Thomas L.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "live-event-puces-typo",
      title: "Puces Typo · live event",
      description: "Série stories live event + récap carrousel.",
      category: "JPO & Events",
      audience: "Lycéens 16-20",
      platform: "Instagram Story",
      tone: "orange",
      rating: 4.7,
      monthlyUsage: 11,
      variables: "{event},{intervenant}",
      body: "Prépare un dispositif stories live pour {event} avec {intervenant}. 6-8 stories : teaser, coulisses, quotes, sondage, récap. Carrousel de clôture avec 5 apprentissages.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "erasmus-candidature",
      title: "Erasmus+ · appel à candidature",
      description: "Post LinkedIn + story, témoignage étudiant·e en mobilité.",
      category: "Recrutement étudiants",
      audience: "Lycéens 16-20",
      platform: "LinkedIn",
      tone: "turquoise",
      rating: 4.4,
      monthlyUsage: 6,
      variables: "{etudiant},{destination},{deadline}",
      body: "Crée un post LinkedIn Erasmus+ avec le témoignage de {etudiant} à {destination}. Angle : expérience vécue, compétences acquises. CTA dépôt candidature avant {deadline}.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "alternance-recrutement-motion",
      title: "Alternance · offre motion design",
      description: "Post LinkedIn pour une offre d'alternance motion design à pourvoir.",
      category: "Recrutement alternance",
      audience: "Lycéens 16-20",
      platform: "LinkedIn",
      tone: "purple",
      rating: 4.5,
      monthlyUsage: 13,
      variables: "{entreprise},{poste},{rythme},{contact}",
      body: "Rédige un post LinkedIn annonçant une alternance chez {entreprise}, poste {poste}, rythme {rythme}. Missions concrètes, compétences attendues, ambiance studio. CTA : postuler via {contact}.",
      author: "Thomas L.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "post-instagram-jpo-mai",
      title: "Instagram · JPO de mai",
      description: "Post Instagram pour promouvoir la JPO de mai, ton complice.",
      category: "Social media",
      audience: "Lycéens 16-20",
      platform: "Instagram",
      tone: "yellow",
      rating: 4.8,
      monthlyUsage: 20,
      variables: "{date},{formations_phares}",
      body: "Rédige un post Instagram pour promouvoir la JPO du {date}. Mets en avant {formations_phares}, ton direct, tutoiement. Carrousel plan du campus + horaires. CTA : inscription en bio.",
      author: "Laure R.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "email-parcoursup-phase-complementaire",
      title: "Email · Parcoursup phase complémentaire",
      description: "Email Parcoursup pour les lycéens en phase complémentaire.",
      category: "Newsletter",
      audience: "Lycéens 16-20",
      platform: "Email",
      tone: "sky",
      rating: 4.6,
      monthlyUsage: 9,
      variables: "{formation},{places_restantes},{deadline}",
      body: "Crée un email Parcoursup phase complémentaire pour {formation}. Objet accrocheur, accroche rassurante, {places_restantes} places, étapes candidature, deadline {deadline}. Signature Laure Reymond.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "alumni-temoignage-site",
      title: "Site web · témoignage alumni",
      description: "Témoignage alumni structuré prêt à intégrer sur la page Alumni du site.",
      category: "Communication officielle",
      audience: "Alumni",
      platform: "Site web",
      tone: "caramel",
      rating: 4.5,
      monthlyUsage: 5,
      variables: "{alumni},{promotion},{job_actuel}",
      body: "Rédige un témoignage alumni en 3 paragraphes : parcours CFI ({promotion}), transition vers {job_actuel}, conseils aux futurs étudiants. 180 mots max. Ton {alumni} incarné.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "annonce-evenement-salon",
      title: "Événements · salon étudiants",
      description: "Kit communication complet pour un salon étudiants : post, story, email.",
      category: "Événements",
      audience: "Lycéens 16-20",
      platform: "Multi-canal",
      tone: "pink",
      rating: 4.4,
      monthlyUsage: 8,
      variables: "{salon},{stand},{dates}",
      body: "Crée un kit salon étudiants pour {salon} stand {stand}, dates {dates}. 1 post Instagram annonce, 3 stories J-3/J-1/Jour J, 1 email base lycéens inscrits. Cohérence visuelle CFI.",
      author: "Thomas L.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "newsletter-alumni-mensuelle",
      title: "Newsletter · alumni mensuelle",
      description: "Trame newsletter alumni mensuelle : actus, portrait, opportunités.",
      category: "Newsletter",
      audience: "Alumni",
      platform: "Email",
      tone: "caramel",
      rating: 4.7,
      monthlyUsage: 6,
      variables: "{mois},{portrait},{offre_alternance}",
      body: "Structure une newsletter alumni de {mois} : édito chaleureux, portrait {portrait}, 3 actus campus, {offre_alternance}, save-the-date événement suivant. Signature communauté.",
      author: "Laure R.",
      favorite: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "communication-officielle-rentree",
      title: "Officielle · communiqué de rentrée",
      description: "Communiqué officiel pour la rentrée de septembre, ton institutionnel.",
      category: "Communication officielle",
      audience: "Entreprises partenaires",
      platform: "Site web",
      tone: "purple",
      rating: 4.2,
      monthlyUsage: 4,
      variables: "{effectif},{nouvelles_formations},{partenariats}",
      body: "Rédige un communiqué officiel de rentrée : effectif {effectif}, {nouvelles_formations}, {partenariats} renouvelés. Ton institutionnel, vouvoiement, 250 mots.",
      author: "Thomas L.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "portfolio-etudiant-carrousel",
      title: "Portfolio · carrousel étudiant",
      description: "Carrousel Instagram pour mettre en avant un portfolio étudiant.",
      category: "Showcase étudiants",
      audience: "Lycéens 16-20",
      platform: "Instagram",
      tone: "lila",
      rating: 4.6,
      monthlyUsage: 12,
      variables: "{etudiant},{projets},{specialite}",
      body: "Compose un carrousel 5 slides portfolio {etudiant} en {specialite}. Slides : intro + photo, {projets}, témoignage, contact. Ton inspirant, mise en avant des crédits.",
      author: "Laure R.",
      favorite: false,
      createdAt: now,
      updatedAt: now,
    },
  ]).run();

  db.insert(personas).values([
    {
      slug: "lyceens-16-20",
      name: "Lycéens 16-20",
      label: "Recrutement · Bac",
      avatarInitial: "L",
      avatarColor: "yellow",
      audienceSize: "720 ciblables",
      performance: "+42% engagement",
      toneOfVoice:
        "Direct, complice, tutoiement systématique. Humour visuel, références culture pop.",
      ageRange: "16-20 ans",
      locationLabel: "Île-de-France majoritaire, +30% hors région",
      educationLevel: "Seconde, Première, Terminale, bac +1",
      preferredPlatforms: serializeList("Instagram Reel", "TikTok", "Stories"),
      vocabularyYes: serializeList("tu", "viens", "check", "atelier", "projet", "ouf", "cool"),
      vocabularyNo: serializeList(
        "vous",
        "notre établissement",
        "cursus",
        "dispositif",
        "clientèle",
      ),
      goals: serializeList(
        "Trouver une formation créative concrète",
        "Se projeter dans un métier",
        "Voir des projets d'étudiants réels",
        "Être rassuré·e sur le parcours",
      ),
      painPoints: serializeList(
        "Parcoursup anxiogène",
        "Peur du jury",
        "Doute sur le débouché pro",
        "Parents sceptiques sur l'art",
      ),
      keyMessages: serializeList(
        "100% projets dès la 1re année",
        "Intervenants pros actifs",
        "Campus accessible métro",
        "Alumni dans les studios reconnus",
      ),
      engagementRate: "9,2%",
      bestHour: "18h-21h",
      topContent: serializeList(
        "Reel atelier sérigraphie - 12,4% engagement",
        "Story J-3 Parcoursup - 8,8% clic",
        "Carrousel 'Une journée type' - 9,1%",
      ),
      recommendations: serializeList(
        "Reel behind-the-scenes hebdo",
        "Story sondage projection métier",
        "Carrousel témoignage étudiant",
        "Live TikTok Q&A admissions",
      ),
      sampleBrief:
        "Annoncer l'ouverture des inscriptions pour le Mastère DCDG rentrée 2026.",
      sampleCopy:
        "T'as une idée fixe : bosser en motion design, direction artistique, 3D. Nous aussi. Mastère DCDG · 2 ans · 100% projets. Les inscriptions sont ouvertes. Viens. 👉 lien bio",
    },
    {
      slug: "parents-etudiants",
      name: "Parents d'étudiants",
      label: "Décideurs · financeurs",
      avatarInitial: "P",
      avatarColor: "sky",
      audienceSize: "310 ciblables",
      performance: "+18% clic brochure",
      toneOfVoice:
        "Rassurant, clair, factuel. Vouvoiement. Chiffres et insertion pro mis en avant.",
      ageRange: "42-58 ans",
      locationLabel: "France entière, urbain et péri-urbain",
      educationLevel: "Bac +3 à bac +5 en majorité",
      preferredPlatforms: serializeList("LinkedIn", "Email", "Facebook", "Instagram feed"),
      vocabularyYes: serializeList(
        "formation",
        "diplôme",
        "insertion",
        "partenaires",
        "alternance",
        "suivi",
      ),
      vocabularyNo: serializeList("ouf", "viens", "tu", "stylé"),
      goals: serializeList(
        "S'assurer du sérieux du diplôme",
        "Comprendre les débouchés",
        "Visualiser le financement",
        "Rencontrer les équipes",
      ),
      painPoints: serializeList(
        "Peur d'un mauvais investissement",
        "Manque de repères sur les métiers créatifs",
        "Inquiétude sur l'emploi",
        "Processus Parcoursup complexe",
      ),
      keyMessages: serializeList(
        "Titres RNCP reconnus",
        "94% d'insertion à 6 mois",
        "Alternance possible",
        "Accompagnement individualisé",
      ),
      engagementRate: "4,8%",
      bestHour: "12h-14h",
      topContent: serializeList(
        "Carrousel 'Insertion pro' - 7,2% clic",
        "Post témoignage parent - 5,4%",
        "Email brochure formation - 18% ouverture",
      ),
      recommendations: serializeList(
        "Webinaire trimestriel",
        "Post LinkedIn chiffres clés",
        "Témoignage parent + enfant",
        "Email fiche formation téléchargeable",
      ),
      sampleBrief:
        "Annoncer l'ouverture des inscriptions pour le Mastère DCDG rentrée 2026.",
      sampleCopy:
        "Le Mastère Direction de Création en Design Graphique forme en 2 ans des directeur·rices artistiques recherché·es. 94% d'insertion à 6 mois. Dossier + entretien. Inscriptions ouvertes jusqu'au 30 juin.",
    },
    {
      slug: "entreprises-partenaires",
      name: "Entreprises partenaires",
      label: "B2B · alternance / workshops",
      avatarInitial: "E",
      avatarColor: "pink",
      audienceSize: "84 comptes",
      performance: "12 nouveaux contrats",
      toneOfVoice:
        "Professionnel, concis, orienté compétences. Vouvoiement. Preuves par projets étudiants.",
      ageRange: "30-55 ans, DA et RH",
      locationLabel: "Paris, Île-de-France, Lyon, Bordeaux",
      educationLevel: "Décideurs studios, agences, marques",
      preferredPlatforms: serializeList("LinkedIn", "Email", "Site partenaires"),
      vocabularyYes: serializeList(
        "savoir-faire",
        "pédagogie",
        "workshop",
        "talents",
        "brief réel",
        "livraison",
      ),
      vocabularyNo: serializeList("stylé", "ouf", "super cool"),
      goals: serializeList(
        "Identifier de jeunes talents",
        "Lancer un workshop co-construit",
        "Capter des alternants qualifiés",
        "Renforcer leur marque employeur",
      ),
      painPoints: serializeList(
        "Difficulté à trouver des alternants formés",
        "Qualité variable d'autres écoles",
        "Manque de visibilité sur les projets",
        "Process RH lourd",
      ),
      keyMessages: serializeList(
        "Profils opérationnels dès l'alternance",
        "Workshops co-brandés disponibles",
        "Alumni dans les studios phares",
        "Process de sourcing simple",
      ),
      engagementRate: "3,1%",
      bestHour: "09h-11h",
      topContent: serializeList(
        "Post LinkedIn workshop Publicis - 6,1%",
        "Case study alternance - 4,2%",
        "Email directeurs artistiques - 22% ouverture",
      ),
      recommendations: serializeList(
        "Post LinkedIn mensuel case study",
        "Webinaire annuel partenariats",
        "Mail ciblé DA avec portfolios",
        "Invitation JPO entreprises",
      ),
      sampleBrief:
        "Annoncer l'ouverture des inscriptions pour le Mastère DCDG rentrée 2026.",
      sampleCopy:
        "Le Mastère DCDG forme en 2 ans des profils DA seniors. Alternance possible dès septembre 2026. Pour recevoir les portfolios de la promo sortante, un mail suffit : partenariats@cfi.fr.",
    },
    {
      slug: "alumni",
      name: "Alumni",
      label: "Communauté · fierté",
      avatarInitial: "A",
      avatarColor: "caramel",
      audienceSize: "4 200 diplômé·es",
      performance: "+31% taux d'ouverture",
      toneOfVoice:
        "Chaleureux, nostalgique mais actuel. Tutoiement ou vouvoiement selon génération. Références partagées.",
      ageRange: "22-45 ans",
      locationLabel: "France, Europe, international (12%)",
      educationLevel: "Bac +3 à bac +5 CFI",
      preferredPlatforms: serializeList("Email", "LinkedIn", "Instagram", "Événements"),
      vocabularyYes: serializeList(
        "promo",
        "atelier",
        "prof-ref",
        "campus",
        "projet signature",
        "réseau",
      ),
      vocabularyNo: serializeList("ancien·nes", "étudiants", "à vous de jouer"),
      goals: serializeList(
        "Rester connecté·e à la promo",
        "Recruter via le réseau",
        "Mentor un·e plus jeune",
        "Voir l'évolution de l'école",
      ),
      painPoints: serializeList(
        "Sentiment d'éloignement post-diplôme",
        "Peu de sollicitations pertinentes",
        "Plateformes alumni peu actives ailleurs",
        "Peu de temps dispo",
      ),
      keyMessages: serializeList(
        "Ton réseau CFI est actif",
        "Ta promo se retrouve chaque année",
        "Tes projets étudiants valorisés",
        "Tes recos comptent pour recruter",
      ),
      engagementRate: "7,4%",
      bestHour: "20h-22h",
      topContent: serializeList(
        "Newsletter portrait - 31% ouverture",
        "Post LinkedIn retrouvailles - 8,4%",
        "Story 'Où sont-ils' - 6,9%",
      ),
      recommendations: serializeList(
        "Newsletter mensuelle portrait",
        "Événement promo physique annuel",
        "Post LinkedIn rétrospective",
        "Email offres d'emploi exclusives",
      ),
      sampleBrief:
        "Annoncer l'ouverture des inscriptions pour le Mastère DCDG rentrée 2026.",
      sampleCopy:
        "Tu connais la promo. Tu vois les projets qui sortent. Le Mastère DCDG rentrée 2026 ouvre ses candidatures. Une promo à parrainer ? Une recommandation à faire ? On écoute 💌",
    },
  ]).run();

  db.insert(alumni).values([
    {
      name: "Mina Roussel",
      graduationYear: 2020,
      currentRole: "Lead motion designer",
      company: "Studio Flamme",
      skills: serializeList("Motion design", "Branding", "After Effects"),
      bio: "Pilote des campagnes social video pour des marques culturelles et intervient sur les jurys de fin d’année.",
    },
    {
      name: "Rayan El Fassi",
      graduationYear: 2018,
      currentRole: "Creative technologist",
      company: "TypoLab",
      skills: serializeList("Creative coding", "Identité", "Expérience interactive"),
      bio: "Conçoit des installations éditoriales et relie design, narration et prototypes pour des lancements de marque.",
    },
    {
      name: "Camille Dorsin",
      graduationYear: 2016,
      currentRole: "Head of social creative",
      company: "Maison Moka",
      skills: serializeList("Direction artistique", "Social media", "Campagne école"),
      bio: "Recrute régulièrement dans le réseau alumni et accompagne les briefs admissions à forte contrainte éditoriale.",
    },
    {
      name: "Noémi Caradec",
      graduationYear: 2021,
      currentRole: "Designer éditoriale",
      company: "Éditions Relief",
      skills: serializeList("Design éditorial", "Typographie", "Mise en page"),
      bio: "Travaille sur des narrations print et web au long cours avec un fort niveau d’exigence typographique.",
    },
    {
      name: "Yanis Belfort",
      graduationYear: 2019,
      currentRole: "Brand designer",
      company: "Collectif 36",
      skills: serializeList("Brand system", "Affiche", "Activation campus"),
      bio: "Spécialisé dans les identités culturelles et les systèmes visuels déclinables pour événements étudiants.",
    },
    {
      name: "Lila Maret",
      graduationYear: 2022,
      currentRole: "Social video strategist",
      company: "Pixel Parade",
      skills: serializeList("TikTok", "Hooks", "Montage"),
      bio: "Optimise les premières secondes des formats courts et aide les équipes à structurer leurs séries vidéo.",
    },
    {
      name: "Alexis Nguyen",
      graduationYear: 2017,
      currentRole: "Design lead",
      company: "Signal Studio",
      skills: serializeList("UX writing", "Système de design", "Pitch client"),
      bio: "Dirige des équipes pluridisciplinaires et intervient comme mentor sur les présentations de concepts.",
    },
    {
      name: "Sonia Baccar",
      graduationYear: 2023,
      currentRole: "Junior art director",
      company: "Atelier Nacre",
      skills: serializeList("DA", "Campagne sociale", "Storyboard"),
      bio: "Fraîchement diplômée, active sur les campagnes social media lifestyle et les tournages légers.",
    },
    {
      name: "Hugo Marchal",
      graduationYear: 2015,
      currentRole: "Creative producer",
      company: "Northwave",
      skills: serializeList("Production", "Brief client", "Planning"),
      bio: "Fait le lien entre stratégie, planning et fabrication sur des productions multicanales à cadence élevée.",
    },
    {
      name: "Jeanne Silva",
      graduationYear: 2024,
      currentRole: "Freelance content designer",
      company: "Indépendante",
      skills: serializeList("UGC", "LinkedIn", "Newsletter"),
      bio: "Développe des kits éditoriaux pour petites équipes et documente ses apprentissages auprès des promos récentes.",
    },
  ]).run();

  db.insert(partners).values([
    {
      name: "Studio Flamme",
      sector: "Motion design",
      partnershipType: "alternance",
      contactEmail: "talents@studioflamme.fr",
      description: "Accueil de profils motion et participation régulière aux jurys portfolio.",
    },
    {
      name: "Maison Moka",
      sector: "Marque lifestyle",
      partnershipType: "stage",
      contactEmail: "creative@maisonmoka.fr",
      description: "Briefs de campagnes admissions et stages courts en direction artistique social media.",
    },
    {
      name: "Pixel Parade",
      sector: "Contenu social",
      partnershipType: "mentorat",
      contactEmail: "mentorat@pixelparade.fr",
      description: "Programme mentorat pour DA junior et coaching portfolio en visio chaque mois.",
    },
    {
      name: "Collectif 36",
      sector: "Événementiel culturel",
      partnershipType: "alternance",
      contactEmail: "studio@collectif36.fr",
      description: "Co-construction d’identités visuelles d’événements étudiants et accompagnement production.",
    },
    {
      name: "Signal Studio",
      sector: "Produit numérique",
      partnershipType: "stage",
      contactEmail: "hello@signalstudio.fr",
      description: "Accueil de profils hybrides design éditorial et interface pour des missions de recherche et prototype.",
    },
  ]).run();

  db.insert(references).values([
    {
      title: "Gobelins · campagne portes ouvertes verticale",
      url: "https://example.com/gobelins-jpo-vertical",
      category: "Campagnes écoles",
      tags: serializeList("JPO", "vertical video", "étudiants"),
      notes: "Bonne alternance entre social proof, plans atelier et CTA inscription en moins de 20 secondes.",
      score: 93,
      createdAt: "2026-04-01T10:00:00+02:00",
    },
    {
      title: "TikTok design trend · texte ultra-court + cut rapide",
      url: "https://example.com/tiktok-fast-cut",
      category: "Hooks social media",
      tags: serializeList("hook", "TikTok", "montage"),
      notes: "Hook texte en 4 mots, preuve visuelle immédiate, rythme soutenu sur 12 secondes.",
      score: 91,
      createdAt: "2026-04-02T10:00:00+02:00",
    },
    {
      title: "Bench visuel carousel portfolio étudiant",
      url: "https://example.com/portfolio-carousel",
      category: "Benchmarks visuels",
      tags: serializeList("portfolio", "carousel", "mise en page"),
      notes: "Structure très claire pour montrer progression concept, prototypes et résultat final.",
      score: 88,
      createdAt: "2026-04-03T10:00:00+02:00",
    },
    {
      title: "LISAA · teasing concours créatif",
      url: "https://example.com/lisaa-concours",
      category: "Campagnes écoles",
      tags: serializeList("concours", "teasing", "campagne"),
      notes: "Bonne mécanique de révélation en 3 temps avec codes couleur simples et angle ambition métier.",
      score: 86,
      createdAt: "2026-04-04T10:00:00+02:00",
    },
    {
      title: "Moodboard typographique signalétique expo",
      url: "https://example.com/type-signaletique",
      category: "Tendances design",
      tags: serializeList("typographie", "signalétique", "expo"),
      notes: "Très bon usage d’une grille rigoureuse et de contrastes forts pour la hiérarchie des infos.",
      score: 84,
      createdAt: "2026-04-05T10:00:00+02:00",
    },
    {
      title: "Hook Reels · avant/après storyboard",
      url: "https://example.com/reels-storyboard",
      category: "Hooks social media",
      tags: serializeList("Reels", "avant-après", "storyboard"),
      notes: "Le basculement avant/après arrive dès la seconde 2 et maintient la curiosité jusqu’au CTA.",
      score: 89,
      createdAt: "2026-04-06T10:00:00+02:00",
    },
    {
      title: "Gobelins alumni portrait LinkedIn",
      url: "https://example.com/gobelins-alumni-linkedin",
      category: "Campagnes écoles",
      tags: serializeList("alumni", "LinkedIn", "portrait"),
      notes: "Format très crédible pour valoriser un parcours sans perdre la preuve concrète du métier.",
      score: 92,
      createdAt: "2026-04-07T10:00:00+02:00",
    },
    {
      title: "Trend social · captions manuscrites sur rush atelier",
      url: "https://example.com/captions-atelier",
      category: "Tendances design",
      tags: serializeList("caption", "atelier", "rush"),
      notes: "Surcouche éditoriale très simple qui humanise les images atelier et rend le contenu plus mémorable.",
      score: 83,
      createdAt: "2026-04-08T10:00:00+02:00",
    },
    {
      title: "Benchmark visuel mini-site portfolio promo",
      url: "https://example.com/mini-site-promo",
      category: "Benchmarks visuels",
      tags: serializeList("mini-site", "promo", "portfolio"),
      notes: "Répartition claire entre navigation, galerie projets et témoignages, avec un ton premium mais accessible.",
      score: 87,
      createdAt: "2026-04-09T10:00:00+02:00",
    },
    {
      title: "Hook face cam + preuve campus immédiate",
      url: "https://example.com/facecam-campus",
      category: "Hooks social media",
      tags: serializeList("face cam", "campus", "preuve"),
      notes: "Ouvre par une question courte, enchaîne directement sur la preuve visuelle et la réponse utile.",
      score: 85,
      createdAt: "2026-04-10T10:00:00+02:00",
    },
    {
      title: "Campagne école alternance en 3 chiffres",
      url: "https://example.com/alternance-3-chiffres",
      category: "Campagnes écoles",
      tags: serializeList("alternance", "preuve sociale", "LinkedIn"),
      notes: "Bon angle chiffres-clés pour rassurer parents et entreprises sans surcharger le visuel.",
      score: 90,
      createdAt: "2026-04-11T10:00:00+02:00",
    },
    {
      title: "Trend design · collage éditorial matières",
      url: "https://example.com/collage-matieres",
      category: "Tendances design",
      tags: serializeList("collage", "matière", "editorial"),
      notes: "Texture et découpe donnent du caractère sans perdre la lisibilité des messages courts.",
      score: 82,
      createdAt: "2026-04-12T10:00:00+02:00",
    },
    {
      title: "Benchmark page témoignages alumni",
      url: "https://example.com/testimonials-board",
      category: "Benchmarks visuels",
      tags: serializeList("témoignages", "alumni", "social proof"),
      notes: "Très bon rythme entre citation, portrait et call-to-action de mise en relation.",
      score: 88,
      createdAt: "2026-04-13T10:00:00+02:00",
    },
    {
      title: "Hook social media · top 3 erreurs portfolio",
      url: "https://example.com/top3-portfolio",
      category: "Hooks social media",
      tags: serializeList("top 3", "portfolio", "conseil"),
      notes: "Très fort potentiel de sauvegarde grâce à une promesse claire et des erreurs concrètes.",
      score: 86,
      createdAt: "2026-04-14T10:00:00+02:00",
    },
    {
      title: "Campagne Gobelins x festival avec code couleur unique",
      url: "https://example.com/gobelins-festival",
      category: "Campagnes écoles",
      tags: serializeList("festival", "code couleur", "événement"),
      notes: "Système simple et très déclinable pour posts, stories, affiches et signalétique campus.",
      score: 94,
      createdAt: "2026-04-15T10:00:00+02:00",
    },
  ]).run();
}

main()
  .then(() => {
    sqlite.close();
  })
  .catch((error) => {
    sqlite.close();
    console.error(error);
    process.exit(1);
  });
